language: node_js

node_js:
  - 8

jobs:
  include:
    - stage: release
      if: branch = master and type = push
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release --branch master
